name: deploy
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Check Output
        run: echo "publishing release for catalyst-maven-plugin-$RELEASE_VERSION"
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: deployment
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Replace Secret
          run: sed -i "s/{{__CATALYST_CLIENT_SECRET__}}/$CATALYST_CLIENT_SECRET/g" src/main/java/com/zoho/catalyst/auth/Oauth2Auth.java
          env:
            CATALYST_CLIENT_SECRET: ${{ secrets.CATALYST_CLIENT_SECRET }}
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
